package com.adpilot.modules.advertising.service.impl;

import com.adpilot.common.exception.BusinessException;
import com.adpilot.common.security.CurrentUser;
import com.adpilot.common.security.DataScopeService;
import com.adpilot.common.security.ScopeTarget;
import com.adpilot.common.utils.SecurityUtils;
import com.adpilot.modules.advertising.converter.SmartDiagnosisConverter;
import com.adpilot.modules.advertising.dto.SmartDiagnosisCreateRequest;
import com.adpilot.modules.advertising.entity.CampaignEntity;
import com.adpilot.modules.advertising.entity.CampaignProductLinkEntity;
import com.adpilot.modules.advertising.entity.RecommendationEntity;
import com.adpilot.modules.advertising.entity.SmartDiagnosisTaskEntity;
import com.adpilot.modules.advertising.mapper.CampaignMapper;
import com.adpilot.modules.advertising.mapper.CampaignProductLinkMapper;
import com.adpilot.modules.advertising.mapper.KeywordMapper;
import com.adpilot.modules.advertising.mapper.RecommendationMapper;
import com.adpilot.modules.advertising.mapper.SmartDiagnosisTaskMapper;
import com.adpilot.modules.advertising.mapper.TargetMapper;
import com.adpilot.modules.advertising.service.RecommendationEngineService;
import com.adpilot.modules.advertising.service.SmartDiagnosisService;
import com.adpilot.modules.advertising.support.AdMetrics;
import com.adpilot.modules.advertising.support.RecommendationDeduplicator;
import com.adpilot.modules.advertising.vo.SmartDiagnosisTaskVo;
import com.adpilot.modules.product.entity.ProductEntity;
import com.adpilot.modules.product.mapper.ProductMapper;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Smart Diagnosis implementation (Req 22). Creating a task runs a diagnosis
 * synchronously: it reuses {@link RecommendationEngineService} to analyze the
 * store's ad structure, aggregates campaign metrics for the diagnosis summary,
 * and derives the diagnosed issues from both direct structural checks and the
 * recommendations generated by this run. When the store has no ad-structure
 * data the diagnosis returns an explicit "insufficient data" result rather than
 * a misleading empty/healthy one.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SmartDiagnosisServiceImpl implements SmartDiagnosisService {

    private final SmartDiagnosisTaskMapper diagnosisTaskMapper;
    private final CampaignMapper campaignMapper;
    private final CampaignProductLinkMapper campaignProductLinkMapper;
    private final RecommendationMapper recommendationMapper;
    private final KeywordMapper keywordMapper;
    private final TargetMapper targetMapper;
    private final ProductMapper productMapper;
    private final RecommendationEngineService recommendationEngineService;
    private final DataScopeService dataScopeService;
    private final ObjectMapper objectMapper;

    /** Store + owner scope target, mirroring campaigns/portfolios. */
    private static final ScopeTarget DIAGNOSIS_SCOPE = ScopeTarget.storeAndOwner("store_id", "created_by");

    /** Max number of issues surfaced in a diagnosis result. */
    private static final int MAX_ISSUES = 50;

    private static CurrentUser scopeUser() {
        return SecurityUtils.isAuthenticated() ? SecurityUtils.getCurrentUser() : null;
    }

    @Override
    @Transactional
    public SmartDiagnosisTaskVo createTask(SmartDiagnosisCreateRequest request, String userId) {
        UUID storeUuid = parseUuid(request.getStoreId(), "storeId");

        // Diagnosis (a trend/structure computation) is requested for a Store; reject
        // when the caller does not own that Store (Req 25.3) without disclosing data.
        CurrentUser actingUser = scopeUser();
        if (actingUser != null) {
            dataScopeService.assertCanWrite(
                    com.adpilot.modules.advertising.support.StoreScopeRef.of(storeUuid), actingUser);
        }

        SmartDiagnosisTaskEntity entity = SmartDiagnosisTaskEntity.builder()
                .storeId(storeUuid)
                .parentAsin(request.getParentAsin().trim())
                .updateFrequency(normalizeFrequency(request.getUpdateFrequency()))
                .status("running")
                .createdBy(userId != null ? UUID.fromString(userId) : null)
                .build();
        diagnosisTaskMapper.insert(entity);

        // Run the diagnosis over the product's ad structure (Req 22.2). Reuse
        // the recommendation engine to surface structural issues, then build a
        // structured result. Failures are isolated so the task is still created.
        try {
            SmartDiagnosisTaskVo.DiagnosisResult result = runDiagnosis(request.getStoreId(), storeUuid,
                    request.getParentAsin().trim());
            entity.setResultJson(objectMapper.writeValueAsString(result));
            entity.setStatus("completed");
            entity.setLastDiagnosedAt(LocalDateTime.now());
        } catch (Exception ex) {
            log.warn("Smart diagnosis failed for task {} (asin={}): {}",
                    entity.getId(), entity.getParentAsin(), ex.getMessage());
            entity.setStatus("failed");
        }
        diagnosisTaskMapper.updateById(entity);

        log.info("Smart diagnosis task created: id={}, asin={}, status={}",
                entity.getId(), entity.getParentAsin(), entity.getStatus());
        return SmartDiagnosisConverter.toVo(entity, objectMapper);
    }

    @Override
    public List<SmartDiagnosisTaskVo> listTasks(String storeId) {
        QueryWrapper<SmartDiagnosisTaskEntity> wrapper = new QueryWrapper<>();
        if (storeId != null && !storeId.isBlank()) {
            wrapper.eq("store_id", parseUuid(storeId, "storeId"));
        }
        CurrentUser user = scopeUser();
        if (user != null) {
            dataScopeService.applyScope(wrapper, DIAGNOSIS_SCOPE, user);
        }
        wrapper.orderByDesc("created_at");

        List<SmartDiagnosisTaskEntity> tasks = diagnosisTaskMapper.selectList(wrapper);
        return tasks.stream()
                .map(t -> SmartDiagnosisConverter.toVo(t, objectMapper))
                .collect(Collectors.toList());
    }

    @Override
    public SmartDiagnosisTaskVo getTaskById(String id) {
        SmartDiagnosisTaskEntity entity = diagnosisTaskMapper.selectById(parseUuid(id, "id"));
        if (entity == null) {
            throw new BusinessException("DIAGNOSIS_NOT_FOUND", "Smart diagnosis task not found: " + id);
        }
        CurrentUser user = scopeUser();
        if (user != null) {
            dataScopeService.assertCanRead(entity, user);
        }
        return SmartDiagnosisConverter.toVo(entity, objectMapper);
    }

    /**
     * Run the diagnosis over the store's ad structure for the given parent ASIN.
     * Reuses {@link RecommendationEngineService} to surface keyword/target/budget
     * issues, adds direct campaign-level structural checks, and derives a health
     * score. Returns an explicit "insufficient data" result when the store has no
     * ad-structure data to analyze.
     */
    private SmartDiagnosisTaskVo.DiagnosisResult runDiagnosis(String storeId, UUID storeUuid, String parentAsin) {
        // Resolve the campaigns associated with the diagnosed parent ASIN via
        // campaign_product_links (Req 46.1, 46.2). The diagnosis is scoped strictly
        // to these campaigns and the records under them; everything outside the
        // parent ASIN is excluded from the result.
        Set<UUID> scopedCampaignIds = resolveCampaignIdsForParentAsin(storeUuid, parentAsin);

        // Aggregate the parent ASIN's campaigns (the ad structure under analysis).
        List<CampaignEntity> campaigns = scopedCampaignIds.isEmpty()
                ? List.of()
                : campaignMapper.selectList(new QueryWrapper<CampaignEntity>()
                        .eq("store_id", storeUuid)
                        .in("id", scopedCampaignIds));

        long keywordCount = scopedCampaignIds.isEmpty() ? 0L : keywordMapper.selectCount(
                new LambdaQueryWrapper<com.adpilot.modules.advertising.entity.KeywordEntity>()
                        .eq(com.adpilot.modules.advertising.entity.KeywordEntity::getStoreId, storeUuid)
                        .in(com.adpilot.modules.advertising.entity.KeywordEntity::getCampaignId, scopedCampaignIds));
        long targetCount = scopedCampaignIds.isEmpty() ? 0L : targetMapper.selectCount(
                new LambdaQueryWrapper<com.adpilot.modules.advertising.entity.TargetEntity>()
                        .eq(com.adpilot.modules.advertising.entity.TargetEntity::getStoreId, storeUuid)
                        .in(com.adpilot.modules.advertising.entity.TargetEntity::getCampaignId, scopedCampaignIds));

        ProductEntity product = resolveProduct(storeUuid, parentAsin);

        // No ad-structure data at all -> explicit insufficient-data result (not a
        // misleading "healthy" score). This is a completed, legitimate outcome.
        if (campaigns.isEmpty() && keywordCount == 0 && targetCount == 0) {
            String missing = product == null
                    ? "未找到该父 ASIN 对应的商品，且没有与该父 ASIN 关联的广告活动/关键词/投放数据。"
                    : "没有与该父 ASIN 关联的广告活动、关键词或投放数据，无法分析其广告结构。";
            return SmartDiagnosisTaskVo.DiagnosisResult.builder()
                    .dataAvailable(false)
                    .summary("数据不足：" + missing + "请先同步或导入广告数据后再诊断。")
                    .campaignCount(0)
                    .enabledCampaignCount(0)
                    .totalSpend(0d)
                    .totalSales(0d)
                    .acos(0d)
                    .issueCount(0)
                    .highCount(0)
                    .mediumCount(0)
                    .lowCount(0)
                    .healthScore(0)
                    .issues(List.of())
                    .build();
        }

        // Reuse the recommendation engine over the store's ad structure (Req 22.2),
        // capturing only the recommendations generated by this run so repeated
        // diagnoses do not accumulate stale issues.
        Set<UUID> beforeIds = pendingRecommendationIds(storeUuid);
        try {
            recommendationEngineService.generateRecommendations(storeId);
        } catch (Exception ex) {
            log.warn("Recommendation engine failed during diagnosis (store={}): {}", storeId, ex.getMessage());
        }

        // One deduplicator per diagnosis pass, reusing the same suppression the
        // recommendation engine uses (Req 46.3, 46.4). Seed it with the store's
        // existing unapplied Recommendations so a diagnosis finding never duplicates
        // an already-pending Recommendation for the same target+change.
        RecommendationDeduplicator dedup = new RecommendationDeduplicator();
        seedExistingRecommendations(storeUuid, dedup);

        BigDecimal totalSpend = BigDecimal.ZERO;
        BigDecimal totalSales = BigDecimal.ZERO;
        int enabledCount = 0;
        for (CampaignEntity c : campaigns) {
            if (c.getSpend() != null) totalSpend = totalSpend.add(c.getSpend());
            if (c.getSales() != null) totalSales = totalSales.add(c.getSales());
            if ("enabled".equalsIgnoreCase(c.getStatus())) enabledCount++;
        }
        double acos = AdMetrics.acos(totalSpend, totalSales).doubleValue();

        List<SmartDiagnosisTaskVo.DiagnosisIssue> issues = new ArrayList<>();

        // 1) Direct campaign-level structural checks — these produce concrete
        //    issues even when there is no keyword/target-level data.
        addStructuralIssues(issues, campaigns, enabledCount, totalSpend, totalSales, acos, product);

        // 2) Issues derived from the recommendations this run produced, restricted to
        //    the parent ASIN's campaigns (Req 46.2) and gated through the shared
        //    duplicate-suppression so the same target+change is surfaced at most once
        //    and never duplicates an existing Recommendation (Req 46.3, 46.4).
        List<RecommendationEntity> recommendations = newRecommendations(storeUuid, beforeIds);
        for (RecommendationEntity rec : recommendations) {
            if (issues.size() >= MAX_ISSUES) break;
            if (rec.getCampaignId() == null || !scopedCampaignIds.contains(rec.getCampaignId())) {
                continue; // outside the diagnosed parent ASIN — excluded (Req 46.2)
            }
            if (!dedup.tryEmit(targetEntityType(rec), targetEntityId(rec), rec.getType())) {
                continue; // duplicate of an existing/already-surfaced change — suppressed
            }
            String priority = rec.getPriority() != null ? rec.getPriority() : "medium";
            issues.add(SmartDiagnosisTaskVo.DiagnosisIssue.builder()
                    .type(rec.getType())
                    .priority(priority)
                    .title(rec.getTitle())
                    .description(rec.getDescription())
                    .build());
        }

        int high = 0;
        int medium = 0;
        int low = 0;
        for (SmartDiagnosisTaskVo.DiagnosisIssue issue : issues) {
            switch (issue.getPriority() != null ? issue.getPriority().toLowerCase() : "medium") {
                case "high" -> high++;
                case "low" -> low++;
                default -> medium++;
            }
        }

        int issueCount = issues.size();
        int healthScore = computeHealthScore(high, medium, low);

        String productLabel = product != null && StringUtils.hasText(product.getName())
                ? "「" + product.getName() + "」" : "父 ASIN " + parentAsin;
        String summary = issueCount == 0
                ? "已分析 " + productLabel + " 的广告结构（" + campaigns.size() + " 个广告活动），未发现明显结构性问题，健康评分 " + healthScore + "。"
                : "已分析 " + productLabel + " 的广告结构，发现 " + issueCount + " 项问题（高 " + high + " / 中 " + medium + " / 低 " + low + "），健康评分 " + healthScore + "。";

        return SmartDiagnosisTaskVo.DiagnosisResult.builder()
                .dataAvailable(true)
                .summary(summary)
                .campaignCount(campaigns.size())
                .enabledCampaignCount(enabledCount)
                .totalSpend(totalSpend.doubleValue())
                .totalSales(totalSales.doubleValue())
                .acos(acos)
                .issueCount(issueCount)
                .highCount(high)
                .mediumCount(medium)
                .lowCount(low)
                .healthScore(healthScore)
                .issues(issues)
                .build();
    }

    /** Resolve the store product matching the parent ASIN, if any. */
    private ProductEntity resolveProduct(UUID storeUuid, String parentAsin) {
        if (!StringUtils.hasText(parentAsin)) {
            return null;
        }
        LambdaQueryWrapper<ProductEntity> w = new LambdaQueryWrapper<>();
        w.eq(ProductEntity::getStoreId, storeUuid)
                .eq(ProductEntity::getAsin, parentAsin.trim())
                .last("LIMIT 1");
        return productMapper.selectOne(w);
    }

    /** IDs of the store's currently-pending recommendations. */
    private Set<UUID> pendingRecommendationIds(UUID storeUuid) {
        QueryWrapper<RecommendationEntity> w = new QueryWrapper<>();
        w.eq("store_id", storeUuid).eq("status", "pending").select("id");
        return recommendationMapper.selectList(w).stream()
                .map(RecommendationEntity::getId)
                .collect(Collectors.toCollection(HashSet::new));
    }

    /** The store's pending recommendations not present before this diagnosis run. */
    private List<RecommendationEntity> newRecommendations(UUID storeUuid, Set<UUID> beforeIds) {
        QueryWrapper<RecommendationEntity> w = new QueryWrapper<>();
        w.eq("store_id", storeUuid).eq("status", "pending").orderByDesc("created_at");
        return recommendationMapper.selectList(w).stream()
                .filter(r -> !beforeIds.contains(r.getId()))
                .collect(Collectors.toList());
    }

    /**
     * Resolve the campaign ids associated with the diagnosed parent ASIN via
     * {@code campaign_product_links} (Req 46.1). These ids define the diagnosis
     * scope: only these campaigns and the records under them are analyzed, and
     * everything outside is excluded from the result (Req 46.2).
     */
    private Set<UUID> resolveCampaignIdsForParentAsin(UUID storeUuid, String parentAsin) {
        if (!StringUtils.hasText(parentAsin)) {
            return Collections.emptySet();
        }
        LambdaQueryWrapper<CampaignProductLinkEntity> w = new LambdaQueryWrapper<>();
        w.eq(CampaignProductLinkEntity::getStoreId, storeUuid)
                .eq(CampaignProductLinkEntity::getParentAsin, parentAsin.trim());
        return campaignProductLinkMapper.selectList(w).stream()
                .map(CampaignProductLinkEntity::getCampaignId)
                .filter(Objects::nonNull)
                .collect(Collectors.toCollection(HashSet::new));
    }

    /**
     * Seed the deduplicator with keys for the store's existing, not-yet-applied
     * Recommendations so a diagnosis finding never duplicates an already-pending
     * Recommendation for the same target+change (Req 46.3, reusing the Req 18.5
     * suppression).
     */
    private void seedExistingRecommendations(UUID storeUuid, RecommendationDeduplicator dedup) {
        LambdaQueryWrapper<RecommendationEntity> w = new LambdaQueryWrapper<>();
        w.eq(RecommendationEntity::getStoreId, storeUuid)
                .in(RecommendationEntity::getStatus, "pending", "applying", "watching", "local-only");
        for (RecommendationEntity rec : recommendationMapper.selectList(w)) {
            dedup.seed(RecommendationDeduplicator.keyOf(targetEntityType(rec), targetEntityId(rec), rec.getType()));
        }
    }

    /** The target object kind for a Recommendation, mirroring the recommendation engine. */
    private static String targetEntityType(RecommendationEntity rec) {
        if (rec.getKeywordId() != null) {
            return "keyword";
        }
        if (rec.getTargetId() != null) {
            return "target";
        }
        return "campaign";
    }

    /** The target object id for a Recommendation, mirroring the recommendation engine. */
    private static UUID targetEntityId(RecommendationEntity rec) {
        if (rec.getKeywordId() != null) {
            return rec.getKeywordId();
        }
        if (rec.getTargetId() != null) {
            return rec.getTargetId();
        }
        return rec.getCampaignId();
    }

    /**
     * Add direct campaign-level structural issues so the diagnosis is concrete
     * even when keyword/target data is sparse.
     */
    private void addStructuralIssues(List<SmartDiagnosisTaskVo.DiagnosisIssue> issues,
                                     List<CampaignEntity> campaigns,
                                     int enabledCount,
                                     BigDecimal totalSpend,
                                     BigDecimal totalSales,
                                     double acos,
                                     ProductEntity product) {
        if (campaigns.isEmpty()) {
            issues.add(issue("structure", "high", "缺少广告活动",
                    "该商品尚未投放任何广告活动，建议创建广告活动以获得曝光与流量。"));
            return;
        }
        if (enabledCount == 0) {
            issues.add(issue("structure", "high", "无投放中的广告活动",
                    "共有 " + campaigns.size() + " 个广告活动，但没有处于投放状态的活动，当前无法获得广告流量。"));
        }

        // Overall ACoS too high (only meaningful when there are sales).
        if (totalSales.compareTo(BigDecimal.ZERO) > 0 && acos > 40d) {
            issues.add(issue("acos", "high", "整体 ACoS 偏高",
                    "整体 ACoS 约为 " + String.format("%.1f", acos) + "%，超过 40%，建议优化高花费低转化的投放或下调竞价。"));
        }

        // Spend with no sales at the store level.
        if (totalSpend.compareTo(BigDecimal.ZERO) > 0 && totalSales.compareTo(BigDecimal.ZERO) <= 0) {
            issues.add(issue("waste", "high", "有花费但无广告销售额",
                    "广告产生了花费但没有带来销售额，建议检查投放相关性与商品详情页转化能力。"));
        }

        // Per-campaign checks: wasted spend and missing budget.
        int wasteCampaigns = 0;
        int noBudgetCampaigns = 0;
        for (CampaignEntity c : campaigns) {
            BigDecimal spend = c.getSpend() != null ? c.getSpend() : BigDecimal.ZERO;
            BigDecimal sales = c.getSales() != null ? c.getSales() : BigDecimal.ZERO;
            if (spend.compareTo(BigDecimal.valueOf(5)) > 0 && sales.compareTo(BigDecimal.ZERO) <= 0) {
                wasteCampaigns++;
            }
            if ("enabled".equalsIgnoreCase(c.getStatus())
                    && (c.getBudget() == null || c.getBudget().compareTo(BigDecimal.ZERO) <= 0)) {
                noBudgetCampaigns++;
            }
        }
        if (wasteCampaigns > 0) {
            issues.add(issue("waste", "medium", "存在花费未产生订单的广告活动",
                    "有 " + wasteCampaigns + " 个广告活动产生了花费但没有销售额，建议复核其关键词与投放设置。"));
        }
        if (noBudgetCampaigns > 0) {
            issues.add(issue("budget", "medium", "投放中广告活动缺少预算",
                    "有 " + noBudgetCampaigns + " 个投放中的广告活动未设置有效预算，可能无法正常获得展示。"));
        }

        // Low inventory context for the diagnosed product.
        if (product != null && product.getInventory() != null && product.getInventory() <= 10) {
            issues.add(issue("inventory", "low", "商品库存偏低",
                    "该商品当前库存为 " + product.getInventory() + "，在加大广告投放前请关注补货，避免断货影响排名。"));
        }
    }

    private SmartDiagnosisTaskVo.DiagnosisIssue issue(String type, String priority, String title, String description) {
        return SmartDiagnosisTaskVo.DiagnosisIssue.builder()
                .type(type)
                .priority(priority)
                .title(title)
                .description(description)
                .build();
    }

    /**
     * Derive a health score in [0,100] from the weighted issue counts. High
     * issues weigh most; a structure with no issues scores 100.
     */
    private int computeHealthScore(int high, int medium, int low) {
        int penalty = high * 15 + medium * 5 + low * 2;
        int score = 100 - penalty;
        return Math.max(0, Math.min(100, score));
    }

    private String normalizeFrequency(String frequency) {
        if (frequency == null || frequency.isBlank()) {
            return "manual";
        }
        String f = frequency.trim().toLowerCase();
        return switch (f) {
            case "manual", "daily", "weekly" -> f;
            default -> throw new BusinessException("INVALID_FREQUENCY",
                    "Unsupported update frequency: " + frequency);
        };
    }

    private UUID parseUuid(String value, String field) {
        try {
            return UUID.fromString(value);
        } catch (IllegalArgumentException | NullPointerException ex) {
            throw new BusinessException("INVALID_ID", "Invalid " + field + ": " + value);
        }
    }
}
