package com.adpilot.modules.ai.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A persisted Insight Agent result (item 16). Every insight generated by the
 * Insight Agent is stored here and retained until the operator manually deletes
 * it, so the saved-insights history survives page reloads.
 *
 * <p>Backed by the additive {@code insight_agent_insights} table. Conventions
 * mirror the other entities: {@code CHAR(36)} ids and JPA + MyBatis-Plus
 * annotations. The {@code recommended_actions} column is a JSON string holding
 * the recommended-action list.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@TableName("insight_agent_insights")
@Table(name = "insight_agent_insights")
public class InsightAgentInsightEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "char(36)")
    private UUID id;

    @Column(name = "store_id", columnDefinition = "char(36)")
    private UUID storeId;

    @Column(name = "query", nullable = false, length = 2000)
    private String query;

    @Column(name = "source", length = 40)
    private String source;

    @Column(name = "premium")
    @Builder.Default
    private Boolean premium = false;

    @Column(name = "insights", columnDefinition = "mediumtext")
    private String insights;

    /** Recommended next actions as a JSON string (list of strings). */
    @Column(name = "recommended_actions", columnDefinition = "json")
    private String recommendedActions;

    /** How the insight was produced (source marker): {@code ai} or {@code degraded}. */
    @Column(name = "generated_by", length = 20)
    private String generatedBy;

    @Column(name = "created_by", columnDefinition = "char(36)")
    private UUID createdBy;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
