package com.adpilot.modules.advertising.hosting;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

/**
 * Default implementation of {@link AiDecisionService}.
 *
 * <p>Persists every AI decision to the {@code ai_decisions} table with an immutable
 * {@link DecisionSnapshot} serialized once at creation via the application's shared
 * {@link ObjectMapper}. The snapshot JSON is never updated after initial write.
 *
 * <p>Validates: Requirements 34.1, 34.2, 34.3, 34.4, 37.1, 37.2, 37.3, 37.5, 13.6.</p>
 */
@Service
public class AiDecisionServiceImpl implements AiDecisionService {

    private final AiDecisionMapper aiDecisionMapper;
    private final ObjectMapper objectMapper;
    private final long defaultDecisionTtlHours;

    public AiDecisionServiceImpl(AiDecisionMapper aiDecisionMapper,
                                 ObjectMapper objectMapper,
                                 @Value("${adpilot.hosting.decision-ttl-hours:4}") long defaultDecisionTtlHours) {
        this.aiDecisionMapper = aiDecisionMapper;
        this.objectMapper = objectMapper;
        this.defaultDecisionTtlHours = defaultDecisionTtlHours;
    }

    @Override
    public AiDecisionEntity createDecision(AiDecisionEntity entity, DecisionSnapshot snapshot) {
        if (entity == null) {
            throw new IllegalArgumentException("entity must not be null");
        }
        if (snapshot == null) {
            throw new IllegalArgumentException("snapshot must not be null");
        }

        // Set decision_expires_at if not already provided (Req 33.1: default 4-hour TTL)
        if (entity.getExpiresAt() == null) {
            entity.setExpiresAt(LocalDateTime.now().plusHours(defaultDecisionTtlHours));
        }

        // Serialize the immutable snapshot to JSON — written once and never updated
        String snapshotJson = serializeSnapshot(snapshot);
        entity.setDecisionSnapshot(snapshotJson);

        // Persist via MyBatis-Plus; UUID is generated by the database/interceptor
        aiDecisionMapper.insert(entity);
        return entity;
    }

    @Override
    public Optional<AiDecisionEntity> findById(UUID id) {
        if (id == null) {
            return Optional.empty();
        }
        return Optional.ofNullable(aiDecisionMapper.selectById(id));
    }

    @Override
    public DecisionSnapshot deserializeSnapshot(AiDecisionEntity entity) {
        if (entity == null) {
            throw new IllegalArgumentException("entity must not be null");
        }
        String json = entity.getDecisionSnapshot();
        if (json == null || json.isBlank()) {
            throw new IllegalArgumentException(
                    "ai_decisions row " + entity.getId() + " has no decision_snapshot");
        }
        try {
            return objectMapper.readValue(json, DecisionSnapshot.class);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException(
                    "Failed to deserialize DecisionSnapshot for ai_decisions row " + entity.getId(), e);
        }
    }

    /**
     * Serializes a {@link DecisionSnapshot} to its canonical JSON form.
     */
    private String serializeSnapshot(DecisionSnapshot snapshot) {
        try {
            return objectMapper.writeValueAsString(snapshot);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to serialize DecisionSnapshot to JSON", e);
        }
    }
}
